// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace BlibT.Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240318073426_in")]
    partial class @in
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("Entities.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "David Johnson"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Emma Brown"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Michael Davis"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Sophia Miller"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Daniel Wilson"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Olivia Moore"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Ethan Lee"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Ava Anderson"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Favorits")
                        .HasColumnType("int");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Pages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Da Vinci Code",
                            Views = 10
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Dune",
                            Views = 10
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Pride and Prejudice",
                            Views = 10
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Girl with the Dragon Tattoo",
                            Views = 10
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Harry Potter and the Sorcerer's Stone",
                            Views = 10
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Great Gatsby",
                            Views = 10
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Steve Jobs",
                            Views = 10
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Hobbit",
                            Views = 10
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "It",
                            Views = 10
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Romeo and Juliet",
                            Views = 10
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Hound of the Baskervilles",
                            Views = 10
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Neuromancer",
                            Views = 10
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 5,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Sense and Sensibility",
                            Views = 10
                        },
                        new
                        {
                            Id = 14,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Girl Who Played with Fire",
                            Views = 10
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Harry Potter and the Chamber of Secrets",
                            Views = 10
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "To Kill a Mockingbird",
                            Views = 10
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Einstein: His Life and Universe",
                            Views = 10
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Lord of the Rings",
                            Views = 10
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "The Shining",
                            Views = 10
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            Description = "Some text",
                            Favorits = 10,
                            Likes = 10,
                            Pages = "[\"text\",\"from\",\"book\"]",
                            Title = "Macbeth",
                            Views = 10
                        });
                });

            modelBuilder.Entity("Entities.Models.BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Entities.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.HasOne("Entities.Models.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Entities.Models.BookGenre", b =>
                {
                    b.HasOne("Entities.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Entities.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("Entities.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
